version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: holmes
    main: ./cmd/main.go
    binary: holmes
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - "jroden2/holmes-go:latest"
      - "jroden2/holmes-go:{{ .Tag }}"
      - "jroden2/holmes-go:v{{ .Major }}"
    dockerfile: Dockerfile
    extra_files:
      - templates/
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

universal_binaries:
  - id: holmes
    replace: true
    name_template: 'holmes'

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - templates/index.html
      - templates/**/*
      - templates/js/*
      - templates/css/*
      - LICENSE
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'