version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: holmes
    main: ./cmd/main.go
    binary: holmes
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - cmd: codesign -s - {{ .Path }}
          os: darwin

universal_binaries:
  - id: holmes
    replace: true
    name_template: 'holmes'

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'