before:
  hooks:
    - go mod tidy

builds:
  - id: holmes
    main: ./cmd/main.go
    binary: holmes
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

universal_binaries:
  - id: holmes
    replace: true
    name_template: 'holmes'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
